### ISSUE TITLE
cpanm is being packaged as part of Class::Plain on CPAN

### ISSUE THREAD

**Issue by tobyink** [yuki-kimoto/Class-Minus#1]
See https://metacpan.org/dist/Class-Plain

You should probably add it to your MANIFEST.SKIP.

**Comment by yuki-kimoto** [comment]
Toby, thanks.

I fixed it now.

https://github.com/yuki-kimoto/Class-Plain/commit/c4e5678298a175d2d3ecadb78b8aafdc5d3dae40
